#!/bin/bash

set -ux

flags=-itd
if [ "${debug:-}" ]; then
  flags=-it
fi

if [ -z "${couchbase_crawl_data:-}" ]; then
  echo 'error: missing couchbase_crawl_data.' >&2
  echo 'Export this variable in your bash profile or ~/.bashrc' >&2
  exit 1
fi

# for some reason haven't got this to work
# --net=host
docker run $flags --rm \
  -v $couchbase_crawl_data:/opt/couchbase/var \
  --name couchbase \
  --ulimit nofile=70000:70000 \
  --ulimit core=100000000:100000000 \
  --ulimit memlock=100000000:100000000  \
  -p 8091-8094:8091-8094 \
  -p 11210:11210 couchbase:community \

if [ -z "${training_crawl_data:-}" -o -z "${training_crawl_repo:-}" ]; then
  echo 'error: missing training_crawl_data and training_crawl_repo variables.' >&2
  echo 'training_crawl_data creates a mysqldata folder wherever you want it on your computer. Example: ~/training-crawl-extra/mysqldata' >&2
  echo 'training_crawl_repo should lead to the directory containing mysqlScripts folder inside this project. Example: ~/training-crawl/03_java_backend' >&2
  echo 'Export these variables in your bash profile or ~/.bashrc' >&2
  exit 1
fi

docker run --rm -p 127.0.0.1:3306:3306/tcp \
  -v $training_crawl_data:/var/lib/mysql \
  -v $training_crawl_repo/mysqlScripts:/mysqlScripts \
  --name mysql \
  -e MYSQL_ROOT_PASSWORD=password \
  -d mariadb:10.5.4

